### ISSUE TITLE
Cannot perfom migration

### ISSUE THREAD

**Issue by CynthiaKamau** [mbbu/sample_management_system#12] opened 2019-11-27 14:12 UTC
File "migrations/env.py", line 30, in <module>
    'SQLALCHEMY_DATABASE_URI').replace('%', '%%'))
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by jeffkim207** [comment] 2019-12-02 07:25
The above issue is caused by flask-migrate(alembic) not finding target meta-data for the models. I have a **temporary** workaround to the issue as I look into a long-term solution on the same. 

Whenever you want to make a migration, in the database.py file, under the migrate_db() function alter the return type to be as shown below;
```
models = [
            Role, User, Theme, Sample,
            Box, Tray, Rack,
            Chamber, Freezer, Laboratory, Publication
        ]

for model in models:
     return model
```

For now, just pull the most current change from **develop** and issue will be fixed.

**Comment by jeffkim207** [comment] 2019-12-02 07:53
> The above issue is caused by flask-migrate(alembic) not finding target meta-data for the models. I have a **temporary** workaround to the issue as I look into a long-term solution on the same.
> 
> Whenever you want to make a migration, in the database.py file, under the migrate_db() function alter the return type to be as shown below;
> 
> ```
> models = [
>             Role, User, Theme, Sample,
>             Box, Tray, Rack,
>             Chamber, Freezer, Laboratory, Publication
>         ]
> 
> for model in models:
>      return model
> ```
> 
> For now, just pull the most current change from **develop** and issue will be fixed.

I have resolved the issue by creating an alternative function, specifically for exporting the models' metadata.

**Comment by CynthiaKamau** [comment] 2019-12-02 09:38
Not working for me

**Comment by CynthiaKamau** [comment] 2019-12-02 09:47
Now its worked

**Comment by jeffkim207** [comment] 2019-12-02 12:22
Great! @CynthiaKamau you can close the issue now if it's fully resolved

**Closed** 2019-12-03 06:29 UTC
